package org.cupula.model.islands.enums;

public enum IlhaCargo {
    PRESIDENTE,
    VICE_PRESIDENTE,
    DEPARTAMENTO_INFRAESTRUTURA,
    DEPARTAMENTO_SAUDE,
    DEPARTAMENTO_RELACOESEXTERNAS,
    DEPARTAMENTO_COMERCIO,
    DEPARTAMENTO_FAZENDA,
    DEPARTAMENTO_SEGURANCA,
    DELEGADO,
    GERAL,
    

}
